#' Posterior Predictive Checks for BDEB Models
#'
#' Extracts replicated data \eqn{y^{\mathrm{rep}}} generated in the Stan
#' `generated quantities` block and pairs them with the observed data
#' \eqn{y}.  Following Gelman et al. (2013, Ch. 6), posterior predictive
#' checks (PPCs) answer: "could the observed data plausibly have been
#' generated by the fitted model?"  If the replicated data envelopes
#' consistently miss systematic features of \eqn{y}, the model is
#' mis-specified.
#'
#' For growth endpoints, the replicated lengths \eqn{L^{\mathrm{rep}}_i}
#' are drawn as \eqn{L^{\mathrm{rep}}_i \sim N(\hat{L}_i, \sigma_L)} in
#' the Stan program.  For reproduction, \eqn{R^{\mathrm{rep}}_i \sim
#' \mathrm{NegBin}(k_R \Delta E_R, \phi)}.
#'
#' @param fit A [bdeb_fit()] object.
#' @param type Which endpoint to check: `"growth"`, `"reproduction"`, or
#'   `"all"`. Default `"growth"`.
#' @return A `bdeb_ppc` object containing observed data (`L_obs` or
#'   `R_obs`), a matrix of replicated data (`L_rep` or `R_rep`), and
#'   metadata for [plot.bdeb_ppc()].
#'
#' @references
#' Gelman, A., Carlin, J.B., Stern, H.S., Dunson, D.B., Vehtari, A.
#' and Rubin, D.B. (2013). *Bayesian Data Analysis*. 3rd edition.
#' Chapman & Hall/CRC. (Chapter 6: Model checking.)
#' @export
bdeb_ppc <- function(fit, type = c("growth", "reproduction", "all")) {
	if (!inherits(fit, "bdeb_fit")) {
		cli::cli_abort("{.arg fit} must be a {.cls bdeb_fit} object.")
	}

	type <- match.arg(type)
	draws <- fit$fit$draws(format = "draws_matrix")

	out <- list(type = type, model_type = fit$model$type)

	# Growth PPC
	if (type %in% c("growth", "all")) {
		L_rep_vars <- grep("^L_rep\\[", colnames(draws), value = TRUE)
		if (length(L_rep_vars) > 0) {
			L_rep <- as.matrix(draws[, L_rep_vars])

			# Get observed data
			if (fit$model$type == "individual") {
				L_obs <- fit$model$stan_data$L_obs
				t_obs <- fit$model$stan_data$t_obs
			} else if (fit$model$type == "growth_repro") {
				L_obs <- fit$model$stan_data$L_obs
				t_obs <- fit$model$stan_data$t_L
			} else {
				L_obs <- NULL
				t_obs <- NULL
			}

			out$growth <- list(
				L_obs = L_obs,
				t_obs = t_obs,
				L_rep = L_rep,
				n_obs = length(L_obs),
				n_draws = nrow(L_rep)
			)
		} else {
			cli::cli_alert_warning("No L_rep found in generated quantities.")
		}
	}

	# Reproduction PPC
	if (type %in% c("reproduction", "all")) {
		R_rep_vars <- grep("^R_rep\\[", colnames(draws), value = TRUE)
		if (length(R_rep_vars) > 0) {
			R_rep <- as.matrix(draws[, R_rep_vars])

			R_obs <- fit$model$stan_data$R_counts

			out$reproduction <- list(
				R_obs = R_obs,
				R_rep = R_rep,
				n_obs = length(R_obs),
				n_draws = nrow(R_rep)
			)
		}
	}

	structure(out, class = "bdeb_ppc")
}

#' @return The input object, invisibly.
#' @export
print.bdeb_ppc <- function(x, ...) {
	cli::cli_h2("BDEB Posterior Predictive Check")
	cli::cli_alert_info("Type: {x$type}")
	if (!is.null(x$growth)) {
		cli::cli_alert("Growth: {x$growth$n_obs} observations, {x$growth$n_draws} posterior draws")
	}
	if (!is.null(x$reproduction)) {
		cli::cli_alert("Reproduction: {x$reproduction$n_obs} intervals, {x$reproduction$n_draws} posterior draws")
	}
	invisible(x)
}

#' Predict from a BDEB Fit
#'
#' Generates posterior predictive trajectories under new environmental
#' conditions or extended time horizons.
#'
#' @param object A [bdeb_fit()] object.
#' @param newdata Optional list with new environmental conditions:
#'   `f_food`, `temperature`, `concentration`, `t_predict`.
#' @param n_draws Number of posterior draws to use. Default 200.
#' @param ... Ignored.
#' @return A `bdeb_prediction` object with predicted trajectories.
#' @export
predict.bdeb_fit <- function(object, newdata = NULL, n_draws = 200, ...) {
	bdeb_predict(object, newdata = newdata, n_draws = n_draws)
}

#' @rdname predict.bdeb_fit
#' @param fit A [bdeb_fit()] object.
#' @export
bdeb_predict <- function(fit, newdata = NULL, n_draws = 200) {
	if (!inherits(fit, "bdeb_fit")) {
		cli::cli_abort("{.arg fit} must be a {.cls bdeb_fit} object.")
	}

	draws <- posterior::as_draws_df(fit$fit$draws())
	n_total <- nrow(draws)
	idx <- sort(sample.int(n_total, min(n_draws, n_total)))

	# Get predicted lengths from fitted model
	L_hat_vars <- grep("^L_hat\\[", names(draws), value = TRUE)

	if (length(L_hat_vars) == 0) {
		cli::cli_alert_warning("No L_hat found. Returning raw posterior draws.")
		return(draws[idx, ])
	}

	L_hat <- as.matrix(draws[idx, L_hat_vars])

	# Get time points
	t_obs <- fit$model$stan_data$t_obs
	if (is.matrix(t_obs)) t_obs <- t_obs[1, ]

	result <- list(
		t         = t_obs,
		L_hat     = L_hat,
		n_draws   = length(idx),
		model_type = fit$model$type,
		newdata   = newdata
	)

	structure(result, class = "bdeb_prediction")
}
