#' Posterior Predictive Checks for BDEB Models
#'
#' Extracts replicated data \eqn{y^{\mathrm{rep}}} generated in the Stan
#' `generated quantities` block and pairs them with the observed data
#' \eqn{y}.  Following Gelman et al. (2013, Ch. 6), posterior predictive
#' checks (PPCs) answer: "could the observed data plausibly have been
#' generated by the fitted model?"  If the replicated data envelopes
#' consistently miss systematic features of \eqn{y}, the model is
#' mis-specified.
#'
#' For growth endpoints, the replicated lengths \eqn{L^{\mathrm{rep}}_i}
#' are drawn as \eqn{L^{\mathrm{rep}}_i \sim N(\hat{L}_i, \sigma_L)} in
#' the Stan program.  For reproduction, \eqn{R^{\mathrm{rep}}_i \sim
#' \mathrm{NegBin}(k_R \Delta E_R, \phi)}.
#'
#' @section Supported models:
#' \describe{
#'   \item{`"individual"`}{Full PPC with `L_rep` and `L_obs`.}
#'   \item{`"growth_repro"`}{Growth PPC via `L_rep`; reproduction PPC
#'     via `R_rep`.}
#'   \item{`"hierarchical"`}{Not available.  The Stan model uses
#'     `reduce_sum` and does not generate `L_rep`.  Use
#'     [bdeb_diagnose()] and trace plots for model checking.}
#'   \item{`"debtox"`}{Not available for the same reason.  Use
#'     [plot_dose_response()] for visual model checking.}
#' }
#'
#' @param fit A [bdeb_fit()] object.
#' @param type Which endpoint to check: `"growth"`, `"reproduction"`, or
#'   `"all"`. Default `"growth"`.
#' @return A `bdeb_ppc` object containing observed data (`L_obs` or
#'   `R_obs`), a matrix of replicated data (`L_rep` or `R_rep`), and
#'   metadata for [plot.bdeb_ppc()].
#'
#' @references
#' Gelman, A., Carlin, J.B., Stern, H.S., Dunson, D.B., Vehtari, A.
#' and Rubin, D.B. (2013). *Bayesian Data Analysis*. 3rd edition.
#' Chapman & Hall/CRC. (Chapter 6: Model checking.)
#' @export
bdeb_ppc <- function(fit, type = c("growth", "reproduction", "all")) {
	if (!inherits(fit, "bdeb_fit")) {
		cli::cli_abort("{.arg fit} must be a {.cls bdeb_fit} object.")
	}

	type <- match.arg(type)

	# Hierarchical and debtox models don't generate L_rep (reduce_sum)
	if (fit$model$type %in% c("hierarchical", "debtox")) {
		cli::cli_abort(c(
			"Posterior predictive checks are not available for {.val {fit$model$type}} models.",
			"i" = "The {.val {fit$model$type}} Stan model uses {.code reduce_sum} and does not generate replicated data.",
			"i" = "Use {.fun bdeb_diagnose} for convergence checks, or {.fun plot_dose_response} for DEBtox."
		))
	}

	draws <- fit$fit$draws(format = "draws_matrix")

	out <- list(type = type, model_type = fit$model$type)

	# Growth PPC
	if (type %in% c("growth", "all")) {
		L_rep_vars <- grep("^L_rep\\[", colnames(draws), value = TRUE)
		if (length(L_rep_vars) > 0) {
			L_rep <- as.matrix(draws[, L_rep_vars])

			if (fit$model$type == "individual") {
				L_obs <- fit$model$stan_data$L_obs
				t_obs <- fit$model$stan_data$t_obs
			} else if (fit$model$type == "growth_repro") {
				L_obs <- fit$model$stan_data$L_obs
				t_obs <- fit$model$stan_data$t_L
			} else {
				# Should not reach here due to guard above
				L_obs <- NULL
				t_obs <- NULL
			}

			out$growth <- list(
				L_obs = L_obs,
				t_obs = t_obs,
				L_rep = L_rep,
				n_obs = length(L_obs),
				n_draws = nrow(L_rep)
			)
		} else {
			cli::cli_alert_warning("No {.var L_rep} found in generated quantities.")
		}
	}

	# Reproduction PPC
	if (type %in% c("reproduction", "all")) {
		R_rep_vars <- grep("^R_rep\\[", colnames(draws), value = TRUE)
		if (length(R_rep_vars) > 0) {
			R_rep <- as.matrix(draws[, R_rep_vars])

			R_obs <- fit$model$stan_data$R_counts

			out$reproduction <- list(
				R_obs = R_obs,
				R_rep = R_rep,
				n_obs = length(R_obs),
				n_draws = nrow(R_rep)
			)
		} else if (type == "reproduction") {
			cli::cli_alert_warning("No {.var R_rep} found in generated quantities.")
		}
	}

	structure(out, class = "bdeb_ppc")
}

#' Prior Predictive Check
#'
#' Simulates growth trajectories by sampling parameters from the prior
#' distributions and forward-integrating the DEB ODE in R (Euler method).
#' This is the prior analogue of [bdeb_ppc()] and answers: "what range
#' of data does the model predict *before seeing any data*?"  Following
#' Gabry et al. (2019), if the prior predictive distribution covers
#' biologically implausible values, the priors should be tightened.
#'
#' Does **not** require CmdStan — all sampling and simulation is done
#' in R using Euler integration (step size `dt`).  This is an
#' **approximate visualisation tool**, not exact Stan inference.  The
#' ODE trajectories may differ slightly from the BDF solver used during
#' fitting.
#'
#' @param model A [bdeb_model()] object.
#' @param n_draws Number of prior draws. Default 500.
#' @param dt Euler step size (days). Default 0.5.
#' @param seed Integer seed for reproducibility. Default `NULL`.
#' @return A list with class `"bdeb_prior_predictive"` containing:
#'   \describe{
#'     \item{`t`}{Time vector.}
#'     \item{`L`}{Matrix of simulated trajectories (draws x time points).}
#'     \item{`L_inf`}{Vector of prior-predictive ultimate lengths.}
#'     \item{`priors`}{Named list of prior objects used.}
#'   }
#'
#' @references
#' Gabry, J., Simpson, D., Vehtari, A., Betancourt, M. and Gelman, A.
#' (2019). Visualization in Bayesian workflow. *Journal of the Royal
#' Statistical Society: Series A*, 182(2), 389--402.
#' \doi{10.1111/rssa.12378}
#'
#' @export
#' @examples
#' dat <- bdeb_data(growth = data.frame(id = 1, time = 0:10,
#'   length = seq(0.1, 0.5, length.out = 11)))
#' mod <- bdeb_model(dat, type = "individual")
#' pp <- bdeb_prior_predictive(mod, n_draws = 100, seed = 1)
#' plot(pp, n_draws = 30)
bdeb_prior_predictive <- function(model, n_draws = 500, dt = 0.5,
                                  seed = NULL) {
	if (!inherits(model, "bdeb_model")) {
		cli::cli_abort("{.arg model} must be a {.cls bdeb_model} object.")
	}

	if (!is.null(seed)) set.seed(seed)

	priors <- model$priors
	f <- model$stan_data$f_food

	# Determine time range from data
	if (model$type == "growth_repro") {
		t_obs <- model$stan_data$t_L
	} else {
		t_obs <- model$stan_data$t_obs
		if (is.matrix(t_obs)) t_obs <- t_obs[1, ]
	}
	t_max <- max(t_obs)
	t_grid <- seq(0, t_max, by = max(dt * 5, 1))

	# Sample from priors
	sample_prior <- function(p, n) {
		switch(p$family,
			lognormal   = stats::rlnorm(n, p$mu, p$sigma),
			normal      = stats::rnorm(n, p$mu, p$sigma),
			beta        = stats::rbeta(n, p$a, p$b),
			halfnormal  = abs(stats::rnorm(n, 0, p$sigma)),
			halfcauchy  = abs(stats::rcauchy(n, 0, p$sigma)),
			exponential = stats::rexp(n, p$rate),
			cli::cli_abort("Unsupported prior family: {.val {p$family}}.")
		)
	}

	p_Am_draws  <- sample_prior(priors$p_Am, n_draws)
	p_M_draws   <- sample_prior(priors$p_M, n_draws)
	kappa_draws <- sample_prior(priors$kappa, n_draws)
	v_draws     <- sample_prior(priors$v, n_draws)
	E_G_draws   <- sample_prior(priors$E_G, n_draws)
	E0_draws    <- sample_prior(priors$E0, n_draws)
	L0_draws    <- sample_prior(priors$L0, n_draws)

	# L_inf from prior
	L_inf_draws <- f * kappa_draws * p_Am_draws / p_M_draws

	# Forward simulate
	L_mat <- matrix(NA_real_, nrow = n_draws, ncol = length(t_grid))

	for (i in seq_len(n_draws)) {
		traj <- sim_deb_lsoda(t_max, p_Am_draws[i], p_M_draws[i],
		                      kappa_draws[i], v_draws[i], E_G_draws[i],
		                      E0_draws[i], L0_draws[i], f, dt = dt)
		L_mat[i, ] <- stats::approx(traj$time, traj$L, xout = t_grid)$y
	}

	result <- list(
		t      = t_grid,
		L      = L_mat,
		L_inf  = L_inf_draws,
		priors = priors,
		f      = f
	)
	structure(result, class = "bdeb_prior_predictive")
}

#' @export
print.bdeb_prior_predictive <- function(x, ...) {
	cli::cli_h2("BDEB Prior Predictive Check")
	cli::cli_alert_info("Draws: {nrow(x$L)}")
	cli::cli_alert_info("Time range: [0, {max(x$t)}]")
	q <- stats::quantile(x$L_inf, c(0.025, 0.5, 0.975), na.rm = TRUE)
	cli::cli_alert("Prior L_inf: median {round(q[2], 2)}, 95% CI [{round(q[1], 2)}, {round(q[3], 2)}]")
	invisible(x)
}

#' @export
plot.bdeb_prior_predictive <- function(x, n_draws = 100, ...) {
	n_total <- nrow(x$L)
	idx <- sort(sample.int(n_total, min(n_draws, n_total)))

	traj_list <- lapply(idx, function(i) {
		data.frame(time = x$t, length = x$L[i, ], draw = i)
	})
	traj_df <- do.call(rbind, traj_list)

	ggplot2::ggplot(traj_df,
	                ggplot2::aes(x = .data$time, y = .data$length,
	                             group = .data$draw)) +
		ggplot2::geom_line(alpha = 0.1, colour = "steelblue") +
		ggplot2::theme_bw() +
		ggplot2::labs(
			title = "Prior Predictive Check: Growth Trajectories",
			subtitle = paste0(nrow(x$L), " draws from prior"),
			x = "Time", y = "Structural Length"
		)
}

#' @return The input object, invisibly.
#' @export
print.bdeb_ppc <- function(x, ...) {
	cli::cli_h2("BDEB Posterior Predictive Check")
	cli::cli_alert_info("Type: {x$type}")
	if (!is.null(x$growth)) {
		cli::cli_alert("Growth: {x$growth$n_obs} observations, {x$growth$n_draws} posterior draws")
	}
	if (!is.null(x$reproduction)) {
		cli::cli_alert("Reproduction: {x$reproduction$n_obs} intervals, {x$reproduction$n_draws} posterior draws")
	}
	invisible(x)
}

#' Predict from a BDEB Fit
#'
#' When `newdata = NULL`, extracts the fitted trajectories (`L_hat`)
#' from the Stan posterior (exact).  When `newdata` is provided, performs
#' **R-side forward simulation** (Euler integration) from the posterior
#' draws under new environmental conditions or extended time horizons.
#' The Euler integrator is an **approximation** — for quantitative
#' results at the original data conditions, prefer `newdata = NULL`.
#'
#' @param object A [bdeb_fit()] object.
#' @param newdata Optional named list with new conditions.  Supported
#'   fields:
#'   \describe{
#'     \item{`t_predict`}{Numeric vector of prediction time points (days).
#'       Required when `newdata` is not `NULL`.}
#'     \item{`f_food`}{Scaled functional response (default: value from
#'       the fitted model).}
#'     \item{`concentration`}{External toxicant concentration (scalar;
#'       only for `"debtox"` models; default 0).}
#'   }
#' @param n_draws Number of posterior draws to use. Default 200.
#' @param dt Euler step size for forward simulation (days). Default 0.5.
#' @param ... Ignored.
#' @return A `bdeb_prediction` object with components `t` (time vector),
#'   `L_hat` (matrix: draws x time points), `n_draws`, `model_type`.
#' @export
predict.bdeb_fit <- function(object, newdata = NULL, n_draws = 200,
                             dt = 0.5, seed = NULL, ...) {
	bdeb_predict(object, newdata = newdata, n_draws = n_draws, dt = dt,
	             seed = seed)
}

#' @rdname predict.bdeb_fit
#' @param fit A [bdeb_fit()] object.
#' @param seed Integer seed for reproducible draw selection.
#'   Default `NULL` (no seed).
#' @export
bdeb_predict <- function(fit, newdata = NULL, n_draws = 200, dt = 0.5,
                         seed = NULL) {
	if (!inherits(fit, "bdeb_fit")) {
		cli::cli_abort("{.arg fit} must be a {.cls bdeb_fit} object.")
	}

	draws <- posterior::as_draws_df(fit$fit$draws())
	n_total <- nrow(draws)
	if (!is.null(seed)) set.seed(seed)
	idx <- sort(sample.int(n_total, min(n_draws, n_total)))

	# --- Case 1: no newdata — return fitted L_hat ---
	if (is.null(newdata)) {
		L_hat_vars <- grep("^L_hat\\[", names(draws), value = TRUE)

		if (length(L_hat_vars) == 0) {
			cli::cli_abort(c(
				"x" = "No {.var L_hat} variables found in posterior draws.",
				"i" = "This model type may not store fitted trajectories in Stan.",
				"i" = "Use {.arg newdata} for R-side forward simulation."
			))
		}

		L_hat <- as.matrix(draws[idx, L_hat_vars])
		if (fit$model$type == "growth_repro") {
			t_obs <- fit$model$stan_data$t_L
		} else {
			t_obs <- fit$model$stan_data$t_obs
			if (is.matrix(t_obs)) t_obs <- t_obs[1, ]
		}

		result <- list(
			t          = t_obs,
			L_hat      = L_hat,
			n_draws    = length(idx),
			model_type = fit$model$type
		)
		return(structure(result, class = "bdeb_prediction"))
	}

	# --- Case 2: newdata — forward simulate in R ---
	if (is.null(newdata$t_predict)) {
		cli::cli_abort("{.arg newdata} must contain {.field t_predict} (numeric time vector).")
	}

	t_pred <- newdata$t_predict
	t_max  <- max(t_pred)
	f_new  <- if (is.null(newdata$f_food)) fit$model$stan_data$f_food else newdata$f_food
	C_w    <- if (is.null(newdata$concentration)) 0 else newdata$concentration
	mtype  <- fit$model$type
	is_tox <- mtype == "debtox"

	L_mat <- matrix(NA_real_, nrow = length(idx), ncol = length(t_pred))

	for (ii in seq_along(idx)) {
		i <- idx[ii]
		p_Am  <- draws$p_Am[i]
		p_M   <- draws$p_M[i]
		kappa <- draws$kappa[i]
		v_val <- draws$v[i]
		E_G   <- draws$E_G[i]
		E0    <- draws$E0[i]
		L0    <- draws$L0[i]

		if (is.null(p_Am)) {
			# Hierarchical: use population-level prediction
			mu <- draws$mu_log_p_Am[i]
			sigma <- draws$sigma_log_p_Am[i]
			p_Am <- exp(stats::rnorm(1, mu, sigma))
			# Use median L0 across individuals
			L0_vars <- grep("^L0\\[", names(draws), value = TRUE)
			if (length(L0_vars) > 0) {
				L0_vals <- vapply(L0_vars, function(v) draws[[v]][i], numeric(1))
				L0 <- stats::median(L0_vals)
			} else {
				L0 <- draws$L0[i]
			}
		}

		if (is_tox) {
			k_d <- draws$k_d[i]
			z_w <- draws$z_w[i]
			b_w <- draws$b_w[i]
			traj <- sim_debtox_lsoda(t_max, p_Am, p_M, kappa, v_val,
			                         E_G, E0, L0, f_new,
			                         k_d, z_w, b_w, C_w, dt = dt)
		} else {
			traj <- sim_deb_lsoda(t_max, p_Am, p_M, kappa, v_val,
			                      E_G, E0, L0, f_new, dt = dt)
		}

		L_mat[ii, ] <- stats::approx(traj$time, traj$L,
		                              xout = t_pred)$y
	}

	result <- list(
		t          = t_pred,
		L_hat      = L_mat,
		n_draws    = length(idx),
		model_type = mtype
	)
	structure(result, class = "bdeb_prediction")
}

#' @export
plot.bdeb_prediction <- function(x, n_draws = 100, ...) {
	n_total <- nrow(x$L_hat)
	idx <- sort(sample.int(n_total, min(n_draws, n_total)))

	traj_list <- lapply(idx, function(i) {
		data.frame(time = x$t, length = as.numeric(x$L_hat[i, ]), draw = i)
	})
	traj_df <- do.call(rbind, traj_list)

	ggplot2::ggplot(traj_df,
	                ggplot2::aes(x = .data$time, y = .data$length,
	                             group = .data$draw)) +
		ggplot2::geom_line(alpha = 0.15, colour = "steelblue") +
		ggplot2::theme_bw() +
		ggplot2::labs(
			title = "Predicted Trajectories",
			subtitle = paste0(length(idx), " posterior draws"),
			x = "Time", y = "Structural Length"
		)
}
